# MIT License
#
# Copyright (c) 2020 Lauritz Timm, Christian Kaltenecker
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - .pre
  - build
  - .post

.template: &template
  cache:
    key: ${CI_PROJECT_ID}
  before_script:
    - lualatex --credits
    - python3 --version
    - latexmk --version
  timeout: 15m

latexmk:
  <<: *template
  stage: build
  script:
    - latexmk -f -quiet BAMA-thesis-NAME.tex
    - latexmk -f -quiet BAMA-proposal-NAME.tex
  after_script:
    - latexmk -c -quiet BAMA-thesis-NAME.tex
    - latexmk -c -quiet BAMA-proposal-NAME.tex
  artifacts:
    paths:
      - BAMA-thesis-NAME.pdf
      - BAMA-proposal-NAME.pdf
    expire_in: 50w

